roles = {
    "Personnage Principal":"ALL",
    "Fratrie":"ALL",
    "Cousin(e)":"ALL",
    "Meilleur ami(e)":"ALL",
    "Ami(e)":"ALL",
    "Voisin(e)":"ALL",
    "Ennemi(e)":"ALL",
    "Pire ennemi(e)":"ALL",
    "Connaissance":"ALL",
    "petit(e) ami(e)":"5+",
    "Fillancé(e)":"5+",
    "Stalker":"16+",
    "Sex Friend":"16+",
    "Collègue":"18+",
    "Epoux/Epouse":"23+",
    "Parent":"26+",
    "Oncle/Tante":"26+",
    "Enfant":"40-",
    "Neveu/Nièce":"40-",
    "Aïeul":"40+"
}