adjectives = [
    "of cold",
    "of ice",
    "of heat",
    "of fire",
    "of wind",
    "of lightning",
    "of blood",
    "of the cross",
    "among the shadows",
    "of dreams",
    "of nightmares",
    "of the sun",
    "of the day",
    "of the night",
    "of the moon",
    "of the sea",
    "of the mountain",
    "of life",
    "of hatred",
    "of destruction",
    "of fear",
    "of shade",
    "of storm",
    "of hurricane",
    "of silence",
    "of death",
    "of tears",
    "of love",
    "of life",
    "with the axe",
    "with the sword",
    "with the hammer",
    "with the eye",
    "with the fangs",
    "with the claws",
    "with the teeth",
    "with the scepter",
    "with the mask",
    "with the hat",
    "with the coat"
]