caracteristics = [
    "Collectionne des cartes à jouer",
    "Ecrit un roman",
    "Souhaite battre un record du monde",
    "Fin gourmet",
    "Lecteur averti",
    "Musicien",
    "Otaku",
    "Croit aux extra-terrestres",
    "Sportif de haut niveau",
    "Bénévole pour une association charitative",
    "Passioné de chimie",
    "Passioné de biologie",
    "Passioné de mathématiques",
    "Passioné d'Echecs",
    "Passioné de jeux vidéos",
    "Passioné de jeux de société",
    "Passioné de Jeux de Role",
    "Passioné d'énigmes",
    "Passioné de pêche",
    "Passioné d'informatique",
    "Fait du Foot",
    "Fait du Yoga",
    "Fait du Judo",
    "Fait du tir à l'arc",
    "Fait son propre alcool",
    "Fait de la potterie",
    "Fait du dessin"
]