styles = [
    "Science fiction",
    "Fantastique",
    "Fantasy",
    "Horreur",
    "Humour",
    "Tranche de vie",
    "Mythologie",
    "Medieval",
    "Space opera",
    "Anticipation",
    "Post apocalypse",
    "Gore/Trash",
    "Drame",
    "Journal intime",
    "Nouvelle",
    "Poésie",
    "Policier",
    "Romance",
    "Thriller",
    "Dark fantasy",
    "De cape et d'épée"
]