roles = {
    "Main Character":"ALL",
    "Sibling":"ALL",
    "Cousin":"ALL",
    "Best friend":"ALL",
    "Friend":"ALL",
    "Neighbor":"ALL",
    "Enemy":"ALL",
    "Worst enemy":"ALL",
    "Acquaintance":"ALL",
    "Boyfriend / Girlfriend":"5+",
    "Fillancé(e)":"5+",
    "Stalker":"16+",
    "Sex Friend":"16+",
    "Colleague":"18+",
    "Husband / Wife":"23+",
    "Parent":"26+",
    "Uncle / Aunt":"26+",
    "Children":"40-",
    "Nephew / Niece":"40-",
    "Aïeul":"40+"
}