styles = [
    "Science fiction",
    "Fantastic",
    "Fantasy",
    "Horror",
    "Humor",
    "Slice of life",
    "Mythology",
    "Medieval",
    "Space opera",
    "Anticipation",
    "Post apocalypse",
    "Gore / Trash",
    "Drama",
    "Personal diary",
    "News",
    "Poetry",
    "Police officer",
    "Romance",
    "Thriller",
    "Dark fantasy",
    "Cloak and sword"
]