caracteristics = [
    "Collect playing cards",
    "Write a novel",
    "Wish to beat a world record",
    "Foodie",
    "Informed reader",
    "Musician",
    "Otaku",
    "Believes aliens exists",
    "Top athlete",
    "Volunteer for a charity",
    "Passionate about chemistry",
    "Passionate about biology",
    "Passionate about mathematics",
    "Passionate about chess",
    "Passionate about video games",
    "Passionate about board games",
    "Passionate about Role Playing",
    "Passionate about riddles",
    "Passionate about fishing",
    "Passionate about computer",
    "Football",
    "Yoga",
    "Judo",
    "Archery",
    "Make his own alcohol",
    "Pottery",
    "Drawing"
]