suffixes = [
    "du froid",
    "de l'eau",
    "de glace",
    "de chaleur",
    "des plantes",
    "de feu",
    "de lave",
    "de vent",
    "de fer",
    "de terre",
    "d'argile",
    "d'acier",
    "de foudre",
    "de sang",
    "de rêves",
    "de nuit",
    "de vie",
    "de mort",
    "de cauchemars",
    "du soleil",
    "du jour",
    "du silence",
    "du destin",
    "des pleurs",
    "des fées",
    "des insectes",
    "des ténèbres",
    "de la lumière",
    "de coeurs",
    "du monde",
    "des armées",
    "de l'amour",
    "de la croix",
    "de la luxure",
    "de la lune",
    "de la mer",
    "de la montagne",
    "de la haine",
    "de la destruction",
    "de la peur",
    "de l'ombre",
    "de la sagesse",
    "de la tempête",
    "de l'avenir",
    "de l'art",
    "des animaux",
    "des vagues",
    "des sable",
    "du désert",
    "de l'ouragan",
    "de la guerre",
    "des plaines",
    "des profondeurs",
    "du val",
    "des rues",
    "des villes",
    "à la hache",
    "à l'épée",
    "au marteau",
    "à l'oeil",
    "aux crocs",
    "aux griffes",
    "aux dents",
    "au sceptre",
    "à l'arc",
    "à la lyre",
    "à la faux",
    "au couteau",
    "aux lames",
    "à la flute",
    "à la guitare",
    "au masque",
    "au chapeau",
    "au manteau",
    "à la bouteille",
    "aux chaînes",
    "aux liens",
    "aux doigts",
    "aux lunettes",
    "aux fidèles",
    "aux alumettes"
]